### ISSUE TITLE
When installing into Visual Studio 2019, It does not check for the correct JSON serialiser and then crashes Visual Studio

### ISSUE THREAD

**Issue by Smurf-IV** [kemmis/Kemmis.MyWorkItemsOnPendingChangesPage#23] opened 2019-05-01 11:40 UTC
- Clean install of Visual Studio 16.03
- Minimal options selected as part of install (To keep footprint small)
- Add "My Work Items" and restart
- Click on "configure your settings" in Pending Changes (TFS 2018)
- Boom 
- System.IO.FileNotFound Exception (Found by attaching the DevEnv in Studio 2017)
- - NewtonSoft.json V 10.0.0.0 dll

**Comment by Smurf-IV** [comment] 2019-05-01 11:43
From https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/
It states that 16 ships with V 9.0.1 of NewtonSoft.json
It also states how to set the extension to use different flavors of NewtonSoft.json

**Comment by Smurf-IV** [comment] 2019-05-01 12:05
Installing "Resharper 2019.1" afterwards allows this control to work.....

**Comment by kemmis** [comment] 2019-05-03 10:55
Oh interesting! I have resharper installed and didn’t get this error. I’ll
try to reproduce this on my side and release a fix today or this weekend.

**Comment by kemmis** [comment] 2019-05-05 13:09
didn't mean to have this automatically close. I still need to publish the darn thing!

**Comment by kemmis** [comment] 2019-05-05 13:20
@Smurf-IV I've published and released version 1.0.13 here: https://marketplace.visualstudio.com/items?itemName=TheRealRafeKemmis.mwivs2019

Would you have a minute to test it out?

**Comment by Smurf-IV** [comment] 2019-05-27 10:54
> @Smurf-IV I've published and released version 1.0.13 here: https://marketplace.visualstudio.com/items?itemName=TheRealRafeKemmis.mwivs2019
> 
> Would you have a minute to test it out?

I missed this.... No, I will not be able to restore back to the "Virgin installation" as it was on one of the companies development machines, which has now "moved on" to the intended dev ....

**Comment by kemmis** [comment] 2019-05-27 15:20
Understood. Thanks again for pointing out this terrible bug. I was working on too many things at the same time... Must have had multiple instances of VS open that day and somehow installed a nuget package or two on this project when I was working on something else entirely... and that somehow went under my radar and got checked in. Craziest dev mistake I've done, possibly ever! Glad nobody's paying me for this one 😊

Anyway, I believe that the latest version is working as intended. It shouldn't be including/referencing a version of newtonsoft that is incompatible with VS 2019.

**Closed as completed by kemmis** 2019-05-27 15:20 UTC
